'use client';

/**
 * AUTO-GENERATED (scratchpad/gen-animated-icon.js). Do not edit by hand.
 * Resolves a lucide icon displayName to an @animateicons/react animated icon
 * (self-animates on hover), falling back to the static lucide icon for the
 * few names the animated library doesn't cover.
 */
import { forwardRef } from 'react';
import type { ForwardRefExoticComponent, RefAttributes } from 'react';
import type { IconHandle } from '@animateicons/react';
import {
  ActivityIcon,
  ArchiveIcon,
  ArrowLeftRightIcon,
  ArrowUpIcon,
  ArrowUpRightIcon,
  BadgeCheckIcon,
  BadgeDollarSignIcon,
  BanknoteIcon,
  BellIcon,
  BookOpenIcon,
  BotIcon,
  BoxesIcon,
  BriefcaseIcon,
  Building2Icon,
  CalendarCheckIcon,
  CalendarClockIcon,
  CalendarDaysIcon,
  CalendarIcon,
  CalendarRangeIcon,
  ChartColumnIcon,
  ChartPieIcon,
  CircleCheckIcon,
  CircleQuestionMarkIcon,
  ClipboardCheckIcon,
  ClipboardListIcon,
  ClockIcon,
  CoinsIcon,
  CompassIcon,
  CreditCardIcon,
  FileMinusIcon,
  FileTextIcon,
  FilterIcon,
  FlameIcon,
  GaugeIcon,
  GitBranchIcon,
  GlobeIcon,
  GraduationCapIcon,
  HandCoinsIcon,
  HashIcon,
  HeadsetIcon,
  HeartIcon,
  HeartPulseIcon,
  HourglassIcon,
  ImageIcon,
  InboxIcon,
  KanbanIcon,
  LandmarkIcon,
  LayersIcon,
  LayoutDashboardIcon,
  LayoutGridIcon,
  LinkIcon,
  ListChecksIcon,
  ListTreeIcon,
  LogOutIcon,
  MailIcon,
  MapPinIcon,
  MegaphoneIcon,
  MenuIcon,
  MessageSquareIcon,
  MessagesSquareIcon,
  MicIcon,
  MonitorSmartphoneIcon,
  MoonIcon,
  PackageIcon,
  PaletteIcon,
  PanelLeftCloseIcon,
  PanelLeftOpenIcon,
  PlaneIcon,
  PlugIcon,
  PlusIcon,
  RadarIcon,
  RadioIcon,
  ReceiptIcon,
  ReceiptTextIcon,
  RotateCcwIcon,
  ScrollTextIcon,
  SearchIcon,
  SettingsIcon,
  ShieldAlertIcon,
  ShieldCheckIcon,
  SlidersHorizontalIcon,
  SparklesIcon,
  StarIcon,
  TableIcon,
  TargetIcon,
  TimerIcon,
  TrendingDownIcon,
  TrendingUpIcon,
  TrophyIcon,
  UmbrellaIcon,
  UndoIcon,
  UserCheckIcon,
  UserPlusIcon,
  UsersIcon,
  UsersRoundIcon,
  WalletIcon,
  WandSparklesIcon,
  WorkflowIcon,
  XIcon,
  ZapIcon,
} from '@animateicons/react/lucide';
import {
  Scale,
} from 'lucide-react';

type IconComp = ForwardRefExoticComponent<
  { size?: number; className?: string } & RefAttributes<IconHandle>
>;

const MAP: Record<string, IconComp> = {
  'Activity': ActivityIcon as unknown as IconComp,
  'Archive': ArchiveIcon as unknown as IconComp,
  'ArrowLeftRight': ArrowLeftRightIcon as unknown as IconComp,
  'ArrowUp': ArrowUpIcon as unknown as IconComp,
  'ArrowUpRight': ArrowUpRightIcon as unknown as IconComp,
  'BadgeCheck': BadgeCheckIcon as unknown as IconComp,
  'Banknote': BanknoteIcon as unknown as IconComp,
  'Bell': BellIcon as unknown as IconComp,
  'BookOpen': BookOpenIcon as unknown as IconComp,
  'Bot': BotIcon as unknown as IconComp,
  'Boxes': BoxesIcon as unknown as IconComp,
  'Briefcase': BriefcaseIcon as unknown as IconComp,
  'BriefcaseBusiness': BriefcaseIcon as unknown as IconComp,
  'BuildingComplex': Building2Icon as unknown as IconComp,
  'Calendar': CalendarIcon as unknown as IconComp,
  'CalendarCheck': CalendarCheckIcon as unknown as IconComp,
  'CalendarClock': CalendarClockIcon as unknown as IconComp,
  'CalendarDays': CalendarDaysIcon as unknown as IconComp,
  'CalendarRange': CalendarRangeIcon as unknown as IconComp,
  'ChartColumn': ChartColumnIcon as unknown as IconComp,
  'ChartPie': ChartPieIcon as unknown as IconComp,
  'CircleCheck': CircleCheckIcon as unknown as IconComp,
  'CircleDollarSign': BadgeDollarSignIcon as unknown as IconComp,
  'CircleQuestionMark': CircleQuestionMarkIcon as unknown as IconComp,
  'ClipboardCheck': ClipboardCheckIcon as unknown as IconComp,
  'ClipboardList': ClipboardListIcon as unknown as IconComp,
  'Clock': ClockIcon as unknown as IconComp,
  'Coins': CoinsIcon as unknown as IconComp,
  'Compass': CompassIcon as unknown as IconComp,
  'CreditCard': CreditCardIcon as unknown as IconComp,
  'FileMinus': FileMinusIcon as unknown as IconComp,
  'FileText': FileTextIcon as unknown as IconComp,
  'Flame': FlameIcon as unknown as IconComp,
  'Funnel': FilterIcon as unknown as IconComp,
  'Gauge': GaugeIcon as unknown as IconComp,
  'GitBranch': GitBranchIcon as unknown as IconComp,
  'Globe': GlobeIcon as unknown as IconComp,
  'GraduationCap': GraduationCapIcon as unknown as IconComp,
  'HandCoins': HandCoinsIcon as unknown as IconComp,
  'Hash': HashIcon as unknown as IconComp,
  'Headset': HeadsetIcon as unknown as IconComp,
  'Heart': HeartIcon as unknown as IconComp,
  'HeartPulse': HeartPulseIcon as unknown as IconComp,
  'Hourglass': HourglassIcon as unknown as IconComp,
  'Images': ImageIcon as unknown as IconComp,
  'Inbox': InboxIcon as unknown as IconComp,
  'Landmark': LandmarkIcon as unknown as IconComp,
  'Layers': LayersIcon as unknown as IconComp,
  'LayoutDashboard': LayoutDashboardIcon as unknown as IconComp,
  'LayoutTemplate': LayoutGridIcon as unknown as IconComp,
  'Link2': LinkIcon as unknown as IconComp,
  'ListChecks': ListChecksIcon as unknown as IconComp,
  'ListTree': ListTreeIcon as unknown as IconComp,
  'LogOut': LogOutIcon as unknown as IconComp,
  'Mail': MailIcon as unknown as IconComp,
  'MapPin': MapPinIcon as unknown as IconComp,
  'Megaphone': MegaphoneIcon as unknown as IconComp,
  'Menu': MenuIcon as unknown as IconComp,
  'MessageSquare': MessageSquareIcon as unknown as IconComp,
  'MessagesSquare': MessagesSquareIcon as unknown as IconComp,
  'Mic': MicIcon as unknown as IconComp,
  'MonitorSmartphone': MonitorSmartphoneIcon as unknown as IconComp,
  'Moon': MoonIcon as unknown as IconComp,
  'Package': PackageIcon as unknown as IconComp,
  'Palette': PaletteIcon as unknown as IconComp,
  'PanelLeftClose': PanelLeftCloseIcon as unknown as IconComp,
  'PanelLeftOpen': PanelLeftOpenIcon as unknown as IconComp,
  'Plane': PlaneIcon as unknown as IconComp,
  'Plug': PlugIcon as unknown as IconComp,
  'Plus': PlusIcon as unknown as IconComp,
  'Radar': RadarIcon as unknown as IconComp,
  'Radio': RadioIcon as unknown as IconComp,
  'Receipt': ReceiptIcon as unknown as IconComp,
  'ReceiptText': ReceiptTextIcon as unknown as IconComp,
  'RotateCcw': RotateCcwIcon as unknown as IconComp,
  'Scale': Scale as unknown as IconComp,
  'ScrollText': ScrollTextIcon as unknown as IconComp,
  'Search': SearchIcon as unknown as IconComp,
  'Settings': SettingsIcon as unknown as IconComp,
  'ShieldAlert': ShieldAlertIcon as unknown as IconComp,
  'ShieldCheck': ShieldCheckIcon as unknown as IconComp,
  'SlidersHorizontal': SlidersHorizontalIcon as unknown as IconComp,
  'Sparkles': SparklesIcon as unknown as IconComp,
  'SquareKanban': KanbanIcon as unknown as IconComp,
  'Star': StarIcon as unknown as IconComp,
  'Table2': TableIcon as unknown as IconComp,
  'Target': TargetIcon as unknown as IconComp,
  'Timer': TimerIcon as unknown as IconComp,
  'TrendingDown': TrendingDownIcon as unknown as IconComp,
  'TrendingUp': TrendingUpIcon as unknown as IconComp,
  'Trophy': TrophyIcon as unknown as IconComp,
  'Umbrella': UmbrellaIcon as unknown as IconComp,
  'Undo2': UndoIcon as unknown as IconComp,
  'UserCheck': UserCheckIcon as unknown as IconComp,
  'UserPlus': UserPlusIcon as unknown as IconComp,
  'Users': UsersIcon as unknown as IconComp,
  'UsersRound': UsersRoundIcon as unknown as IconComp,
  'Wallet': WalletIcon as unknown as IconComp,
  'WandSparkles': WandSparklesIcon as unknown as IconComp,
  'Workflow': WorkflowIcon as unknown as IconComp,
  'X': XIcon as unknown as IconComp,
  'Zap': ZapIcon as unknown as IconComp,
};

const FALLBACK = new Set<string>(['Scale']);

/**
 * Renders the animated version of a lucide icon by its `displayName`.
 * Pass `name={SomeLucideIcon.displayName}`. Attach the `ref` from the library's
 * `useIconHover()` so a parent element's hover can trigger the animation.
 * Returns null for unknown names.
 */
export const AnimatedIcon = forwardRef<
  IconHandle,
  { name?: string; size?: number; className?: string }
>(function AnimatedIcon({ name, size = 16, className }, ref) {
  const C = name ? MAP[name] : undefined;
  if (!C) return null;
  return (
    <C
      ref={name && !FALLBACK.has(name) ? ref : undefined}
      size={size}
      className={className}
    />
  );
});
